FROM golang:1.14-alpine

WORKDIR /api

COPY . /api

## Add this go mod download command to pull in any dependencies
RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon

## Our project will now successfully build with the necessary go libraries included.
ENTRYPOINT CompileDaemon -build="go build main.go" -command="./main" -polling="true"

EXPOSE 5000
