version: "2"
services:
  api:
    build:
      context: ./ 
      dockerfile: Dockerfile.development
    ports:
     - "5000:5000"
    volumes:
     - ./:/api
    links:
     - redis
    environment: 
      CHOKIDAR_USEPOLLING: "true"

  redis:
    image: redis:alpine
    expose:
      - "6379"

